### ISSUE TITLE
Coulomb's Law Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/coulombs-law#7]
## Design
- [x] **Sim folder and design doc created** (Date: 02/22/2017) 
  - [x] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [x] Place design doc in the sim folder
- [x] **Sim suggestions doc reviewed**
- [x] **Learning goals and standards identified** (Date: 02/23/2017)
- [x] **Design concept complete**  (Date: 02/23/2017)
- [x] **Wireframes complete** (Date: 02/28/2017) 
- [x] **Mockups complete** (Date: 03/09/2017) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Features for PhET-iO discussion**  -- see https://github.com/phetsims/inverse-square-law-common/issues/53
- [x] **Interviews complete** (Date: 12/11/2018) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 06/05/2018) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [x] Auxilary screenshots (up to 3 additional)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Guide created, uploaded, and added to sim design folder
  <s>- [ ] Add an activity</s> N/A
  - [x] Sim primer draft -- see #56 
  - [x] Verify credits
  - [x] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [x] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [x] **Post-publication items**
  - [x] Add the simulation to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [x] Add to Edmodo
  - [x] Add to [Gooru](http://gooru.org/PhET/content/resources) (signed in as phethelp)
  - [x] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [x] Sim primer (create issue, publish ideally within 1 month of live sim) -- see #56
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [x] **Repository created** (Date: 02/17/2017)
  - [x] simula-rasa used to create project skeleton
  - [x] README.md created using `grunt unpublished-readme`
  - [x] Collaborators added (such as QA team, designers, etc)
  - [x] standard GitHub label set applied
  - [x] repository added to chipper/data/ files
- [x] **Development started** (Date: 03/16/2017)
- [x] **Sim is "feature complete"** (Date: //) 
- [x] **Code review completed** (Date: //) 
- [x] **Published** (Date: 12/27/18) 
  - [x] README.md updated using `grunt published-readme` (in master and release branch)
 
## QA
- [x] **Dev testing started** (Date: 02/13/2018) 
- [x] **Dev testing completed** (Date: 10/05/2018) 
- [x] **First RC published** (Date: 11/01/2018)
  - [x] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [x] **RC testing completed** (Date: 12/21/2018)

**Comment by arouinfar** [comment]
@ariel-phet the remaining checklist items are yours.
